version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2017
nuget:
  project_feed: true
build_script:
- ps: ./build.ps1
artifacts:
- path: ./Build/nuget/*.nupkg
  name: NuGet